Added models and fixed namespaces
InooGotchi/InnoGotchi pull request #2
Opened 2023-01-10 17:14 UTC by Kartang12

Добавил модельки и починил неймспейсы (у нас тут инногачи, а не клин архитектура)

2023-01-10 17:34 UTC, sdechko1 commented on src/Domain/Common/PetBody.cs
> +public enum NoseTypeEnum
I think you should rename this to `NoseType` so it does not contain Enum

2023-01-11 09:37 UTC, sdechko1 approved these changes

2023-01-11 12:24 UTC, klimenkatechart requested changes

2023-01-11 12:24 UTC, klimenkatechart commented on src/Domain/Common/PetType.cs
> +}
Consider deleting this Class, I think it's a good idea for real-life project, but in your scenario we don't want to overcomplicated things

2023-01-12 10:26 UTC, dakamakat commented on src/Domain/Common/Pet.cs
> +    public int Hunger { get; set; } // 0-3
Consider to use actual enums for these statuses avoid magic numbers in code

2023-01-12 12:25 UTC, Kartang12 commented on src/Domain/Common/PetBody.cs
> +public enum NoseTypeEnum
Done

2023-01-12 12:32 UTC, Kartang12 commented on src/Domain/Common/User.cs
> +    public Guid Id { get; set; }
Done

2023-01-12 12:32 UTC, Kartang12 commented on src/Domain/Common/Pet.cs
> +    public int Hunger { get; set; } // 0-3
true

2023-01-12 12:32 UTC, merged