Background service
InooGotchi/InnoGotchi pull request #4
Opened 2023-02-07 11:45 UTC by dakamakat

2023-02-20 13:50 UTC, Kartang12 commented on src/Infrastructure/Persistence/Configurations/PetBodyConfiguration.cs
> +        builder.HasOne(pb => pb.Pet).WithOne(p => p.Body).HasForeignKey<PetBody>(pb => pb.PetId);
А че тут пустые строки не почистил?)

2023-02-20 13:50 UTC, Kartang12 commented on src/Infrastructure/Services/TokenService.cs
> +                new Claim(ClaimTypes.Name, userName),
А зачем дублировать клеймы? Да, имя их разное, но нагрузка одинаковая.

2023-02-20 18:45 UTC, dakamakat commented on src/Infrastructure/Persistence/Configurations/PetBodyConfiguration.cs
> +        builder.HasOne(pb => pb.Pet).WithOne(p => p.Body).HasForeignKey<PetBody>(pb => pb.PetId);
-___________-

2023-02-21 09:33 UTC, dakamakat commented on src/Infrastructure/Services/TokenService.cs
> +                new Claim(ClaimTypes.Name, userName),
обновил

2023-02-21 09:52 UTC, sdechko1 requested changes

2023-02-21 09:52 UTC, sdechko1 commented on src/Infrastructure/Persistence/Configurations/BodyParts/BodyConfiguration.cs
> +namespace InnoGotchi.Infrastructure.Persistence.Configurations.BodyParts;
мб стоит добавлять пустую строку после неймспейсов для читаемости

2023-02-21 09:52 UTC, sdechko1 commented on src/Infrastructure/Persistence/Configurations/PetConfiguration.cs
> +        builder.Property(farm => farm.Name).HasMaxLength(255).IsRequired();
тут наверное в лямбде не farm, а pet должен быть

2023-02-21 09:52 UTC, sdechko1 commented on src/Domain/Entities/Pet.cs
> +    public DateTime NextDrinkDate { get; set; }
Учитывая, что у нас метод для попойки называется `HydratePet`, то мб стоит назвать поле `NextHydrationDate`

2023-02-21 09:52 UTC, sdechko1 commented on src/Domain/Entities/Player.cs
> +    public Guid ApplicationUserId { get; set; }
класс Player, а тут User, почему так ?

2023-02-21 09:52 UTC, sdechko1 commented on src/Infrastructure/Identity/IdentityService.cs
> +            Email = userName,
а почему тут имейл как юзернейм ?

2023-02-21 09:52 UTC, sdechko1 commented on src/Infrastructure/Persistence/Configurations/BodyParts/EyesConfiguration.cs
> +        builder.HasMany(n => n.PetBodies).WithOne(pb => pb.Eyes);
вместо n e насколько я понимаю в лямбде

2023-02-21 09:52 UTC, sdechko1 commented on src/Infrastructure/Persistence/Configurations/BodyParts/MouthConfiguration.cs
> +        builder.HasMany(n => n.PetBodies).WithOne(pb => pb.Mouth);
а тут m

2023-02-21 09:52 UTC, sdechko1 commented on src/Infrastructure/Persistence/Configurations/PetBodyConfiguration.cs
> +
эту пустую строчечку нафиг

2023-02-21 09:52 UTC, sdechko1 commented on src/Infrastructure/Persistence/Configurations/PetConfiguration.cs
> +
эту пустую тоже нафиг

2023-02-21 09:52 UTC, sdechko1 commented on src/Web/CheckHostedService.cs
> +    }
пустую строчку бы сюда

2023-02-21 09:52 UTC, sdechko1 commented on src/Web/CheckHostedService.cs
> +                }
я предпочитаю после закрывающейся фигурной скобки ставить пустую строку

2023-02-21 09:52 UTC, sdechko1 commented on src/Web/ConfigureServices.cs
> +        var key = configuration["Jwt:Key"];
мб стоит лучше ConfigureOptions тут юзануть? сразу запамить в модель IOptions и ее передавать

2023-02-21 09:52 UTC, sdechko1 commented on src/Web/Controllers/UserController.cs
> +public class UserController : ControllerBase
у нас же есть базовый `ApiController` он атрибуты эти уже имеет

2023-02-21 09:52 UTC, sdechko1 commented on src/Web/Controllers/UserController.cs
> +        string token = _tokenService.GenerateJWTToken((userId, userName));
может вместо явного указания типа для консистенстности вездe var юзать ?

2023-02-21 09:52 UTC, sdechko1 commented on src/Web/Program.cs
> +        var initialiser = scope.ServiceProvider.GetRequiredService<ApplicationDbContextInitialiser>();
наверное правильно Initializer, но я так понимаю, что это уже в клин аркитекче так было

2023-02-21 09:52 UTC, sdechko1 commented on src/Web/Program.cs
>  app.MapControllerRoute(
а нам это разве нужно ?

2023-02-21 09:52 UTC, sdechko1 commented on src/Web/Program.cs
> +app.Use(async (context, next) =>
мб лучше из этого отдельную мидлварку сделать ?

2023-02-21 11:49 UTC, dakamakat commented on src/Domain/Entities/Player.cs
> +    public Guid ApplicationUserId { get; set; }
ApplicationUser это сущность которая используется для авторизации , Player это сущность которая представляет Пользователя в нашем приложении , очень стремно смотрелось когда в domain это User а в Infrastructure это ApplicationUser и учитывая что они разные да и название Player лучше отражает суть как по мне ( Player - domain entity в нашем приложении а ApplicationUser - чисто инфраструктурная 
**Вот ссылки на issue в которых обсуждались оптимальные решения** 

- https://github.com/jasontaylordev/CleanArchitecture/discussions/655
- https://github.com/dotnet-architecture/eShopOnWeb/issues/39
- https://github.com/jasontaylordev/CleanArchitecture/issues/325
По сути все идет к одному решению если мы хотим делать Identity отдельно от нашей Domain и почти везде нейминг в domain так же делают более конкретным чем просто User

2023-02-21 11:50 UTC, dakamakat commented on src/Infrastructure/Identity/IdentityService.cs
> +            Email = userName,
поправил

2023-02-21 11:52 UTC, dakamakat commented on src/Web/Controllers/UserController.cs
> +public class UserController : ControllerBase
поправил

2023-02-21 11:54 UTC, dakamakat commented on src/Web/Program.cs
>  app.MapControllerRoute(
если ты про 44 строку то она удалена , так как она не нужна

2023-02-21 11:56 UTC, sdechko1 commented on src/Web/Program.cs
>  app.MapControllerRoute(
я про MapControllerRoute

2023-02-21 11:56 UTC, dakamakat commented on src/Web/Program.cs
> +app.Use(async (context, next) =>
я это сделал для удобства тестирования и работы , думаю что есть уже готовое решение которое логает все запросы в asp net надо поискать потестить

2023-02-21 11:59 UTC, sdechko1 commented on src/Web/Program.cs
> +app.Use(async (context, next) =>
вполне реально, что оно есть, но если мы свое оставляем, то лучше сделать отдельный мидлвар и просто его тут зарегать

2023-02-21 13:05 UTC, dakamakat commented on src/Web/Program.cs
> +        var initialiser = scope.ServiceProvider.GetRequiredService<ApplicationDbContextInitialiser>();
поправил

2023-02-21 13:05 UTC, dakamakat commented on src/Web/Controllers/UserController.cs
> +        string token = _tokenService.GenerateJWTToken((userId, userName));
поправил

2023-02-21 13:05 UTC, dakamakat commented on src/Web/ConfigureServices.cs
> +        var key = configuration["Jwt:Key"];
поправил

2023-02-21 13:06 UTC, dakamakat commented on src/Web/CheckHostedService.cs
> +                }
обновил job , эту логику перенес в сервис

2023-02-21 13:06 UTC, dakamakat commented on src/Infrastructure/Persistence/Configurations/BodyParts/MouthConfiguration.cs
> +        builder.HasMany(n => n.PetBodies).WithOne(pb => pb.Mouth);
поправил

2023-02-21 13:06 UTC, dakamakat commented on src/Infrastructure/Persistence/Configurations/BodyParts/EyesConfiguration.cs
> +        builder.HasMany(n => n.PetBodies).WithOne(pb => pb.Eyes);
поправил

2023-02-21 13:06 UTC, dakamakat commented on src/Infrastructure/Persistence/Configurations/PetConfiguration.cs
> +        builder.Property(farm => farm.Name).HasMaxLength(255).IsRequired();
поправил

2023-02-21 13:06 UTC, dakamakat commented on src/Infrastructure/Persistence/Configurations/BodyParts/BodyConfiguration.cs
> +namespace InnoGotchi.Infrastructure.Persistence.Configurations.BodyParts;
поправил

2023-02-21 13:27 UTC, dakamakat commented on src/Web/Program.cs
> +app.Use(async (context, next) =>
поправил

2023-02-21 13:58 UTC, dakamakat commented on src/Web/Program.cs
>  app.MapControllerRoute(
да , это позволяет мапить URl  к нашим контроллерам , без этого все будет 404
https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-7.0

2023-02-21 13:58 UTC, dakamakat commented on src/Web/Program.cs
>  app.MapControllerRoute(
можно заменить на app.MapDefaultControllerRoute();

2023-02-22 08:52 UTC, sdechko1 approved these changes

2023-02-22 14:13 UTC, klimenkatechart approved these changes

2023-02-23 08:11 UTC, merged